import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavigationSidebar from "./components/navigation/NavigationSidebar";

const font = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hackathon Chat app",
  description: "Generated by create next app",
};

const MainLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${font.className} dark`}>
        <div className="h-full">
          <div
            className=" h-full w-[72px]
            z-30 flex-col fixed inset-y-0"
          >
            <NavigationSidebar/>
          </div>
          <main className="md:pl-[72px] h-full">{children}</main>
        </div>
      </body>
    </html>
  );
};

export default MainLayout;
